theme: jekyll-theme-architect
title: "Mejora de procesos"
author: "A.M.Mayoral (asun.mayoral@umh.es)"
date: "Septiembre 2020 -Enero 2021"
description: "Repositorio Github para compartir documentación y sintaxis de programación."
