title: Mejora de procesos
author: A.M.Mayoral
email: asun.mayoral@umh.es
twitter_username: asunmayoral
github_username:  asunmayoral 
date: Septiembre 2020 -Enero 2021
description: Repositorio Github para compartir documentación y sintaxis de programación.
theme: jekyll-theme-architect
